### ISSUE TITLE
Provide compatibility with Python 3.x.x

### ISSUE THREAD

**Issue by mmaruniak** [Cimpress-MCP/JustReleaseNotes#19]
Please provide a version compatible with the changes in Python version 3.x.x. The associated issues in JustReleaseNotes are:
- Change the namespaces of imported packages to include the project name as well, e.g. "JustReleaseNotes.package" instead of "package"
- Change the "print" statement to function "print()"
- Wrap the iterators returned by the "keys()" and "map()" functions in gitrepo.py in a sortable type, e.g. a list
- Change the calls "d.iteritems()" to "iter(d.items())" in HtmlWriter.py and MarkdownWriter.py

**Comment by rnowosielski** [comment]
Should be fixed in the next release of the pip package (or in master branch)
