### ISSUE TITLE
Filter git commits by date and/or hash

### ISSUE THREAD

**Issue by istanishev** [Cimpress-MCP/JustReleaseNotes#33]
It would be nice to limit the commits that are processed. For example not older than specific date or commits created only after specific hash.

**Comment by rnowosielski** [comment]
It seems to me the #9 and #33 potentially have synergies. I would even risk a statement that they have the sane underlying cause.

**Comment by rnowosielski** [comment]
@istanishev, do you thin issue #9 solves this problem ? If so close it, otherwise, could you please add the use cases that we would be trying to solve ?

**Comment by istanishev** [comment]
#9 and #33 do have synergy but they serve different purpose. To achieve what #33 provides using  #9, one would have to change in the way how release notes are stored and generated.

**Comment by rnowosielski** [comment]
So I don't understand why I would want to generate release notes with a filter: can you give me an example of such filter and its rationale?

**Comment by istanishev** [comment]
Imagine you have a package that was released in one way but later the release process was changed. We can assume the old version is not published anymore. I would still like to have the release notes for all the versions released the old way (and I don't want to generate them). I would also like once I adapt to the new release process, not to include any older tickets as part of the new release notes.

And yes, #9 can address this but the usage of the release notes tools have to change as well. The users need to ensure the "correct" index file is already there. 

You might also have problems if you release older versions (bug fixes) and you'll have to somehow figure out a way for combining release notes. Let's say you have published versions 1,2,3,4,5 and you need to create v2.1. Depending on how you store/provide the "latest generated release notes" file you might have v2.1 or v5 as latest.

We already have a limit of the commits being processed by JustReleaseNotes (currently, hard coded to 1024) so I see this ticket as a possible extension.

**Comment by mmaruniak** [comment]
Hello, I started working on this issue in https://github.com/mmaruniak/JustReleaseNotes/commits/limit-min-version . @rnowosielski could you please assign this to me?

Also I would like to ask how we want to proceed with incremental generation if a 'ProceedUntilCommit' (naming is not definite, feel free to have suggestions) is set. Is it okay to disable it every time this setting is present?

**Comment by rnowosielski** [comment]
@mmaruniak Done. you have been Assigned :P

**Comment by rnowosielski** [comment]
@mmaruniak Did you ever merge this or have a pull request for it ?

**Comment by rnowosielski** [comment]
Seems this has been fixed long time ago:

config can contain 

```
                    "OldestCommitToProcess" : <commit hexsha>,
                    "ExcludeCommitsWithMessageMatchingRegex" : <regex>
```

that will filter commits.
