### ISSUE TITLE
Provide a way to exclude commits matching specific commit message

### ISSUE THREAD

**Issue by mmaruniak** [Cimpress-MCP/JustReleaseNotes#46]
It would be nice to be able to exclude commits based on their commit message. Depending on the repository being analyzed and it's structure, we might have "system" commits which should be ignored while extracting ticket information.

**Comment by rnowosielski** [comment]
Would such system commits contain a ticket number ? If not then they are not really showing up - other than stability improvement remark, right?

**Comment by istanishev** [comment]
Yes, they do contain a ticket number. The problem we see now is coming from the automatic merges between version branches (gitflow).
